FROM alpine:3

LABEL author="Muhammad Asfian"
LABEL company="AsV03" website="https://github.com/AsV03/sister/tree/main"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"